// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anashasan/gomqtt/pkg/api/handlers"
	"github.com/anashasan/gomqtt/pkg/application/admin"
	"github.com/anashasan/gomqtt/pkg/application/connection"
	"github.com/anashasan/gomqtt/pkg/application/publishing"
	"github.com/anashasan/gomqtt/pkg/application/services"
	"github.com/anashasan/gomqtt/pkg/application/subscribing"
	"github.com/anashasan/gomqtt/pkg/common/clock"
	"github.com/anashasan/gomqtt/pkg/common/logger"
	"github.com/anashasan/gomqtt/pkg/common/uid"
	"github.com/anashasan/gomqtt/pkg/domain/metrics"
	"github.com/anashasan/gomqtt/pkg/domain/persistence"
	"github.com/anashasan/gomqtt/pkg/infrastructure/config"
	prometheus2 "github.com/anashasan/gomqtt/pkg/infrastructure/metrics/prometheus"
	"github.com/anashasan/gomqtt/pkg/infrastructure/persistence/memory"
	"github.com/anashasan/gomqtt/pkg/infrastructure/transport"
	"github.com/google/wire"
	"github.com/prometheus/client_golang/prometheus"
)

// Injectors from wire.go:

// ProvideClock provides the wall clock.
func ProvideClock() clock.Clock {
	systemClock := clock.NewSystemClock()
	return systemClock
}

// ProvideUIDGenerator provides the identifier generator.
func ProvideUIDGenerator() uid.Generator {
	randomGenerator := uid.NewRandomGenerator()
	return randomGenerator
}

// ProvideLogger provides the structured logger.
func ProvideLogger(cfg *config.AppConfig) logger.Logger {
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	return slogLogger
}

// ProvideMetricsRegistry provides the Prometheus registry.
func ProvideMetricsRegistry() *prometheus.Registry {
	registry := prometheus2.NewRegistry()
	return registry
}

// ProvideMetricsRecorder provides the metrics port implementation.
func ProvideMetricsRecorder(registry *prometheus.Registry) metrics.Recorder {
	registerer := provideRegisterer(registry)
	recorder := prometheus2.NewRecorder(registerer)
	return recorder
}

// InjectBroker builds the complete broker graph.
func InjectBroker(cfg *config.AppConfig, recorder metrics.Recorder) *Broker {
	sessionStore := memory.NewSessionStore()
	clientRegistry := memory.NewClientRegistry()
	subscriptionIndex := memory.NewSubscriptionIndex()
	retainedStore := memory.NewRetainedStore()
	systemClock := clock.NewSystemClock()
	logLevel := config.GetLogLevel(cfg)
	slogLogger := provideSlogLogger(logLevel)
	publishingConfig := config.GetPublishingConfig(cfg)
	publishingService := publishing.NewPublishingService(subscriptionIndex, sessionStore, retainedStore, systemClock, recorder, slogLogger, publishingConfig)
	authConfig := config.GetAuthConfig(cfg)
	authenticator := provideAuthenticator(authConfig)
	randomGenerator := uid.NewRandomGenerator()
	connectionConfig := config.GetConnectionConfig(cfg)
	connectionService := connection.NewConnectionService(sessionStore, clientRegistry, subscriptionIndex, publishingService, authenticator, randomGenerator, systemClock, recorder, slogLogger, connectionConfig)
	subscriptionService := subscribing.NewSubscriptionService(sessionStore, subscriptionIndex, publishingService, systemClock, recorder, slogLogger)
	transportHandlers := provideHandlers(connectionService, subscriptionService, publishingService)
	listenerConfig := config.GetListenerConfig(cfg)
	listener := transport.NewListener(transportHandlers, systemClock, recorder, slogLogger, listenerConfig)
	adminService := admin.NewAdminService(sessionStore, clientRegistry, subscriptionIndex, retainedStore, publishingService, systemClock)
	adminHandler := handlers.NewAdminHandler(adminService)
	brokerVersion := config.GetBrokerVersion(cfg)
	supportHandler := provideSupportHandler(brokerVersion)
	handlersHandlers := handlers.NewHandlers(adminHandler, supportHandler)
	broker := newBroker(listener, handlersHandlers, publishingService, sessionStore, subscriptionIndex, clientRegistry, retainedStore, slogLogger)
	return broker
}

// wire.go:

var clockSet = wire.NewSet(clock.NewSystemClock, wire.Bind(new(clock.Clock), new(*clock.SystemClock)))

var uidSet = wire.NewSet(uid.NewRandomGenerator, wire.Bind(new(uid.Generator), new(*uid.RandomGenerator)))

var loggerSet = wire.NewSet(config.GetLogLevel, provideSlogLogger, wire.Bind(new(logger.Logger), new(*logger.SlogLogger)))

// metricsSet binds the recorder and narrows *prom.Registry to the
// prom.Registerer the recorder actually needs — it only registers collectors,
// so it should not be handed a type that can also gather and reset them.
var metricsSet = wire.NewSet(
	provideRegisterer, prometheus2.NewRecorder, wire.Bind(new(metrics.Recorder), new(*prometheus2.Recorder)),
)

var sessionStoreSet = wire.NewSet(memory.NewSessionStore, wire.Bind(new(persistence.ISessionStore), new(*memory.SessionStore)))

var clientRegistrySet = wire.NewSet(memory.NewClientRegistry, wire.Bind(new(persistence.IClientRegistry), new(*memory.ClientRegistry)))

var retainedStoreSet = wire.NewSet(memory.NewRetainedStore, wire.Bind(new(persistence.IRetainedStore), new(*memory.RetainedStore)))

var subscriptionIndexSet = wire.NewSet(memory.NewSubscriptionIndex, wire.Bind(new(persistence.ISubscriptionIndex), new(*memory.SubscriptionIndex)))

var publishingSet = wire.NewSet(config.GetPublishingConfig, publishing.NewPublishingService, wire.Bind(new(services.IPublishingService), new(*publishing.PublishingService)), wire.Bind(new(admin.CounterSource), new(*publishing.PublishingService)))

var connectionSet = wire.NewSet(config.GetConnectionConfig, config.GetAuthConfig, provideAuthenticator, connection.NewConnectionService, wire.Bind(new(services.IConnectionService), new(*connection.ConnectionService)))

var subscribingSet = wire.NewSet(subscribing.NewSubscriptionService, wire.Bind(new(services.ISubscriptionService), new(*subscribing.SubscriptionService)))

var adminSet = wire.NewSet(admin.NewAdminService, wire.Bind(new(services.IAdminService), new(*admin.AdminService)))

// brokerSet is every store and service the broker needs, in one set.
//
// The stores are listed here rather than in each injector because they must be
// *singletons* across the whole graph: the listener and the admin API have to
// see the same subscription index, or the admin API would report an empty
// broker. Wire builds one instance per set per injector, so grouping them is
// what guarantees the sharing.
var brokerSet = wire.NewSet(
	sessionStoreSet,
	clientRegistrySet,
	retainedStoreSet,
	subscriptionIndexSet,

	publishingSet,
	connectionSet,
	subscribingSet,
	adminSet,

	clockSet,
	uidSet,
	loggerSet,
)

// Broker is everything a running broker is made of.
//
// Returned as one struct so the whole graph is built by a single injector call
// and the components that must share a store genuinely do.
type Broker struct {
	Listener   *transport.Listener
	Handlers   *handlers.Handlers
	Publishing *publishing.PublishingService
	Sessions   persistence.ISessionStore
	Index      persistence.ISubscriptionIndex
	Clients    persistence.IClientRegistry
	Retained   persistence.IRetainedStore
	Log        logger.Logger
}

// newBroker assembles the Broker struct. Wire calls it with the graph it built.
func newBroker(
	listener *transport.Listener, handlers2 *handlers.Handlers, publishing2 *publishing.PublishingService,
	sessions persistence.ISessionStore,
	index persistence.ISubscriptionIndex,
	clients persistence.IClientRegistry,
	retained persistence.IRetainedStore,
	log logger.Logger,
) *Broker {
	return &Broker{
		Listener:   listener,
		Handlers:   handlers2,
		Publishing: publishing2,
		Sessions:   sessions,
		Index:      index,
		Clients:    clients,
		Retained:   retained,
		Log:        log,
	}
}
